/**
 * Mock data for development, testing, and fallback when local backend server is offline.
 */

export const MOCK_USERS = [
  {
    id: 'usr_admin_1',
    name: 'Chef Alessandro Rossi',
    email: 'admin@savorybistro.com',
    password: 'password123',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&q=80&w=250',
    title: 'Executive Head Chef & General Manager',
  },
  {
    id: 'usr_cust_2',
    name: 'Sophia Laurent',
    email: 'customer@savorybistro.com',
    password: 'password123',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250',
    title: 'Gourmet Club Member',
  },
];

export const MOCK_DISHES = [
  {
    id: 'dish_1',
    name: 'Truffle Tagliolini',
    category: 'Main Course',
    price: 32.50,
    rating: 4.9,
    reviewsCount: 142,
    description: 'Handmade fresh pasta tossed in cultured butter, 30-month Parmigiano-Reggiano, and freshly shaved black Norcia truffles.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281223?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
    isAvailable: true,
    calories: 620,
    prepTime: '15 mins',
    tags: ['Signature', 'Vegetarian'],
  },
  {
    id: 'dish_2',
    name: 'Pan-Seared Wagyu Ribeye',
    category: 'Main Course',
    price: 58.00,
    rating: 5.0,
    reviewsCount: 218,
    description: 'A5 Miyazaki Wagyu ribeye served with roasted bone marrow butter, smoked shallot jus, and charred baby broccolini.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
    isAvailable: true,
    calories: 840,
    prepTime: '22 mins',
    tags: ['Chef Special', 'Gluten-Free'],
  },
  {
    id: 'dish_3',
    name: 'Wild Salmon Carpaccio',
    category: 'Appetizer',
    price: 24.00,
    rating: 4.8,
    reviewsCount: 95,
    description: 'Thinly sliced Alaskan King Salmon, caper berries, pickled radish, Meyer lemon emulsion, and micro greens.',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
    isAvailable: true,
    calories: 310,
    prepTime: '10 mins',
    tags: ['Raw Bar', 'Keto'],
  },
  {
    id: 'dish_4',
    name: 'Velvety Burrata & Heirloom Peach',
    category: 'Appetizer',
    price: 19.50,
    rating: 4.9,
    reviewsCount: 164,
    description: 'Pugliese burrata, grilled Okanagan peaches, 12-year aged balsamic reduction, toasted pistachios, and fresh basil.',
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb2252c?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
    isAvailable: true,
    calories: 450,
    prepTime: '8 mins',
    tags: ['Vegetarian', 'Seasonal'],
  },
  {
    id: 'dish_5',
    name: 'Grand Cru Dark Chocolate Fondant',
    category: 'Dessert',
    price: 16.00,
    rating: 4.9,
    reviewsCount: 180,
    description: 'Warm molten Valrhona Guanaja 70% chocolate center, Tahitian vanilla bean gelato, and gold leaf flakes.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
    isAvailable: true,
    calories: 520,
    prepTime: '12 mins',
    tags: ['Signature', 'Sweet'],
  },
  {
    id: 'dish_6',
    name: 'Smoked Rosemary Old Fashioned',
    category: 'Beverage',
    price: 18.00,
    rating: 4.7,
    reviewsCount: 88,
    description: 'Small-batch Kentucky bourbon, Angostura bitters, burnt orange peel, flamed rosemary sprig, and hand-carved ice sphere.',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
    isAvailable: true,
    calories: 180,
    prepTime: '5 mins',
    tags: ['Cocktail', 'Craft'],
  },
  {
    id: 'dish_7',
    name: 'Crispy Mediterranean Calamari',
    category: 'Appetizer',
    price: 21.00,
    rating: 4.6,
    reviewsCount: 76,
    description: 'Tender Monterey squid, smoked paprika dust, grilled lemon, and house-made roasted garlic aioli.',
    image: 'https://images.unsplash.com/photo-1604909052743-94e838986d24?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
    isAvailable: true,
    calories: 480,
    prepTime: '12 mins',
    tags: ['Seafood'],
  },
  {
    id: 'dish_8',
    name: 'Artisan Wood-Fired Margherita',
    category: 'Main Course',
    price: 22.00,
    rating: 4.8,
    reviewsCount: 130,
    description: 'San Marzano D.O.P. tomatoes, fresh Fior di Latte mozzarella, extra virgin olive oil, and sweet basil leaves.',
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&q=80&w=800',
    isFeatured: false,
    isAvailable: true,
    calories: 780,
    prepTime: '14 mins',
    tags: ['Classic', 'Vegetarian'],
  },
];

export const MOCK_DASHBOARD_STATS = {
  totalDishes: 24,
  activeDishes: 21,
  pendingOrders: 8,
  todayRevenue: 3845.50,
  monthlyRevenue: 94250.00,
  activeUsers: 1420,
  tableOccupancyRate: '88%',
  averageOrderValue: 74.20,
};

export const MOCK_RECENT_ORDERS = [
  {
    id: 'ORD-9821',
    customer: 'Eleanor Vance',
    items: 'Truffle Tagliolini x2, Old Fashioned x2',
    total: 101.00,
    status: 'Preparing',
    time: '5 mins ago',
    table: 'Table 04',
  },
  {
    id: 'ORD-9820',
    customer: 'Marcus Brody',
    items: 'Pan-Seared Wagyu Ribeye x1, Wine x1',
    total: 78.50,
    status: 'Ready',
    time: '12 mins ago',
    table: 'Table 12',
  },
  {
    id: 'ORD-9819',
    customer: 'Clara Oswald',
    items: 'Burrata Peach x1, Salmon Carpaccio x1',
    total: 43.50,
    status: 'Delivered',
    time: '24 mins ago',
    table: 'Table 02',
  },
  {
    id: 'ORD-9818',
    customer: 'David Tennant',
    items: 'Wagyu Ribeye x2, Fondant x2',
    total: 148.00,
    status: 'Completed',
    time: '45 mins ago',
    table: 'Table 08',
  },
];
